# generated by datamodel-codegen:
#   filename:  get_employees.json
#   timestamp: 2026-04-07T14:33:28+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    id: int
    name: str
    role: str
    salary: float
